{
 "title": "custom Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Unhealthy Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Pod Restarts (Cluster)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container!=\"kube-apiserver\", container!=\"kube-system-fluentd-cloudwatch\", container!=\"etcd-container\", container!=\"weave\"}) by (container, namespace) > 0\n"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "content": "---\n# RabbitMQ\n---",
   "targets": [
    {}
   ]
  },
  {
   "title": "RabbitMQ Channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "RabbitMQ Channels" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_channelsTotal) by (instance, kubernetes_namespace)"
    }
   ]
  },
  {
   "title": "Rabbit Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Rabbit Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_connectionsTotal) by (instance, kubernetes_namespace)\n"
    }
   ]
  },
  {
   "title": "RabbitMQ Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "RabbitMQ Consumers" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_consumersTotal) by (instance, kubernetes_namespace)"
    }
   ]
  },
  {
   "title": "RabbitMQ Exchanges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "RabbitMQ Exchanges" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_exchangesTotal) by (instance, kubernetes_namespace)"
    }
   ]
  }
 ]
}